### ISSUE TITLE
checklist from Marcel on HF code

### ISSUE THREAD

**Issue by bsonghao** [bsonghao/Thermal-Field#2]
- [x] 1. reconstructing GS HF energy from h and V in physical canonical HF basis (MO basis). Also reconstruct the Fock matrix. Compare to PySCF
- [ ] 2. use quasiparticle transform to map bare h and V to ancillary space. Calculate energy and Fock matrix using qp-picture
- [ ] 3. Compare energies and Fock matrix from step 2 to qp-transforming physical Fock matrix from step 1
